// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"eBookTest","status":true,"description":"Adds a database/log feature to the game menu.","parameters":{"Open eBook":"Database"}}
];
