// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Database","status":true,"description":"Database A custom plugin that creates a database or log for the player to access during the game.","parameters":{"menuCommand":"Database","databaseTitle":"Database","databaseCategories":"NPCs, Locations, Clues, Dialogue"}}
];
